{{- if .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis-database.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-database.labels" . | nindent 4 }}
  {{- with .Values.security.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.security.serviceAccount.automountServiceAccountToken }}
{{- end }}
