---
apiVersion: v1
kind: Service
metadata:
  name: session-database-service
  namespace: session-database
  labels:
    app: session-database
spec:
  selector:
    app: session-database
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: ${REDIS_NODEPORT}
      name: redis
  type: NodePort
