apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-database

resources:
  - ../../base

patches:
  - path: patches/resources.yaml
  - path: patches/replicas.yaml
  - path: patches/services.yaml

secretGenerator:
  - name: redis-database-secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
