apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: redis-database

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap-shared.yaml
  - configmap-master.yaml
  - configmap-replica.yaml
  - configmap-sentinel.yaml
  - configmap-acl.yaml
  - service-master.yaml
  - service-replica.yaml
  - service-sentinel.yaml
  - service-headless.yaml
  - statefulset-master.yaml
  - statefulset-replica.yaml
  - deployment-sentinel.yaml

commonLabels:
  app.kubernetes.io/name: redis-database
  app.kubernetes.io/managed-by: kustomize
