apiVersion: v1
kind: Service
metadata:
  name: redis-database-replica-service
  labels:
    app.kubernetes.io/name: redis-database
    app.kubernetes.io/component: redis-replica
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis-database
    app.kubernetes.io/component: redis-replica
